name: Create Python Package

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Create virtual environment && Build Package
        env:
        run: |
          ./build_venv.sh
          source ./venv/bin/activate
          pip list
          python setup.py sdist bdist_wheel
