name: Create Python Package

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python_version: '3.x'

      - name: Create virtual environment
        run: ./build_venv.sh

      - name: Build Deploy package
        run: |
          python setup.py sdist bdist_wheel