name: Create Python Package

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Create virtual environment
        env:
          PYTHONBASE=/tmp/python
        run: |
          cd $PYTHONBASE
          ./build_venv.sh

      - name: pip list
        run: |
          ls -alh $PYTHONBASE/venv/bin/activate
          source $PYTHONBASE/venv/bin/activate
          pip list

      - name: Build Deploy package
        run: |
          source $PYTHONBASE/venv/bin/activate
          python setup.py sdist bdist_wheel